<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-N7T8FIF4" failures="1" tests="5" name="verify in chrome" time="35.229" errors="0" timestamp="2022-10-31T08:30:57 IST">
  <testcase classname="com.supermarket.tests.LogInTest" name="Verify_RememberMeCheckBox" time="0.339"/>
  <testcase classname="com.supermarket.tests.LogInTest" name="verify_InvalidData" time="0.774">
    <failure type="java.lang.AssertionError" message="This is testcase failed expected [× Alert!] but found [×
Alert!
Invalid Username/Password]">
      <![CDATA[java.lang.AssertionError: This is testcase failed expected [× Alert!] but found [×
Alert!
Invalid Username/Password]
at com.supermarket.tests.LogInTest.verify_InvalidData(LogInTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_InvalidData -->
  <testcase classname="com.supermarket.tests.LogInTest" name="verify_LogIn" time="3.578"/>
  <testcase classname="com.supermarket.tests.LogInTest" name="verify_LogOut" time="2.856"/>
  <testcase classname="com.supermarket.tests.PushNotificationTest" name="verify_PushNotification" time="5.843"/>
</testsuite> <!-- verify in chrome -->
